url = ["https://pterclub.net/", "https://pterclub.com/", ]
name = "pter"
nickname = "pterclub"
logo = "favicon.ico"
tracker = "tracker.pterclub.com|tracker.pterclub.net"
sp_full = 125
limit_speed = 100
tags = "高清,综合,游戏,顶级压制,官组"
iyuu = 6
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance-ajax.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = [
    "torrents.php?search={}",
    "music.php?search={}",
    "officialgroup.php?search={}",
]
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlist.php?do_ajax=1&userid={}&type=leeching"
page_uploaded = "getusertorrentlist.php?do_ajax=1&userid={}&type=uploaded"
page_seeding = "userdetails.php?id={}"
page_completed = "getusertorrentlist.php?do_ajax=1&userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='sitefreepool.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//table[@id='bonus-sum']//td[@rowspan]/span/text()"
my_score_rule = "//span[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//span[@class='medium']/span[@class='nowrap']/a[contains(@class,'_Name')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//td[contains(text(),'H&R')]/following-sibling::td/text()"
my_leech_rule = "//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "(//body//b)[1]/text()"
my_seed_rule = "//img[@class='arrowup']/following-sibling::text()[1]"
my_seed_vol_rule = "//td[contains(text(),'做种大小')]/following-sibling::td/text()"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//input[@name='confirm-news']"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//div[1]/a[contains(@href,'detail')]/b/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/div//a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@class"
torrent_poster_rule = ".//td/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following::b[1]/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]//text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]//text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'种子链接')]/following-sibling::td/a/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]/@href"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@class,'torrents-tag')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "0"
downloaded = "50GB"
bonus = 0.0
score = 10000
ratio = 1.05
torrents = 10
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以直接发布种子；可以查看邀请区；可以请求续种；可以上传字幕和删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 10
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 30000
ratio = 1.55
torrents = 20
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "EliteUser可以查看排行榜。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 24
uploaded = "0"
downloaded = "300GB"
bonus = 0.0
score = 80000
ratio = 2.05
torrents = 30
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看排行榜。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 32
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 150000
ratio = 2.55
torrents = 40
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "750GB"
bonus = 0.0
score = 900000
ratio = 3.05
torrents = 50
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看其它用户的评论、帖子历史；封存账号后，不会因不活跃原因被临时封禁。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 48
uploaded = "0"
downloaded = "1024GB"
bonus = 0.0
score = 1800000
ratio = 3.55
torrents = 60
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可 2 次无条件不活跃解封（虽然考虑活跃度，可能远不止 2 次），可以查看邀请树统计，初次升级赠送 1 枚永久邀请码"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 56
uploaded = "0"
downloaded = "1536GB"
bonus = 0.0
score = 3600000
ratio = 4.05
torrents = 70
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "追加 1 次无条件不活跃解封，可以查看邀请树图，初次升级赠送 2 枚永久邀请码"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 112
uploaded = "0"
downloaded = "3072GB"
bonus = 0.0
score = 9600000
ratio = 4.55
torrents = 100
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "四川简州猫及以上用户不会因不活跃原因被临时封禁，初次升级赠送 3 枚永久邀请码。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看 VIP 交流区。免除自动降级。默认的发送邀请最低级别。拥有黄星时，期间免下载量（只有其一时依然计算下载量，下同）"
