url = [ "https://azusa.wiki/", "https://zimiao.icu/",]
name = "梓喵"
nickname = "azusa"
logo = "favicon.ico"
tracker = "tracker.azusa.wiki|tracker.zimiao.icu|zimiao.icu"
sp_full = 300
limit_speed = 100
tags = "漫画,动漫"
iyuu = 0
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = [ "torrents.php?search={}",]
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlist_ajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),'最近')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//font[@class='color_ratio']/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='medal.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//td[contains(text(),'做种积分')]/following-sibling::td/text()[1]"
my_level_rule = "//span/span[@class='nowrap']/a[contains(@class,'_Name')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//span/span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown'][1]/following-sibling::text()[1]"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//img[@class='arrowup'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//body/text()"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td/a[contains(@href,'detail')]/b/text()[last()]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@class"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'种子链接')]/following-sibling::td/a/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。可以直接发布种子。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "50GB"
bonus = 0.0
score = 40000
ratio = 1.0
torrents = 1
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以查看NFO文档；可以查看用户列表；可以请求续种；可以发送邀请；可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "100GB"
bonus = 0.0
score = 100000
ratio = 2.0
torrents = 10
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "EliteUserxa0及以上用户封存账号后不会被删除。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "150G"
bonus = 0.0
score = 300000
ratio = 3.0
torrents = 20
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "200GB"
bonus = 0.0
score = 500000
ratio = 4.0
torrents = 40
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "250GB"
bonus = 0.0
score = 1000000
ratio = 5.0
torrents = 80
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "得到三个邀请名额；可以查看其它用户的评论、帖子历史。VeteranUserxa0及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "300G"
bonus = 0.0
score = 1500000
ratio = 6.0
torrents = 150
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "可以更新过期的外部信息；可以查看ExtremeUser论坛。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "350GB"
bonus = 0.0
score = 2000000
ratio = 7.0
torrents = 150
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "得到五个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "400GB"
bonus = 0.0
score = 5000000
ratio = 8.0
torrents = 300
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "得到十个邀请名额。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。"
