url = ["https://monikadesign.uk/", ]
name = "莫妮卡"
nickname = "monika"
logo = "favicon.ico"
tracker = "monikadesign.uk|tracker.monikadesign.uk|daisuki.monikadesign.uk|daikirai.monikadesign.uk|anime-no-index.com|a.x-anime.cc|A.x-anime.cc"
sp_full = 100
limit_speed = 100
tags = "动漫"
iyuu = 83
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = ""
page_torrents = "torrents"
page_sign_in = "attendance.php"
page_control_panel = "users/{}"
page_detail = "torrents/{}"
page_download = "torrents/download/{}"
page_user = "users/{}"
page_search = ["torrents?perPage=100&name={}", ]
page_message = "mail/inbox"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "users/{}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "users/{}/bonus/formula"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//td[contains(text(),'邀请') and not(contains(text(),'可以'))]/following-sibling::td/span/text()"
my_time_join_rule = "//h4[contains(text(),'注册日期')]/text()"
my_latest_active_rule = "//td[contains(text(),' 上次登录时间')]/following-sibling::td/text()"
my_uploaded_rule = "//li[@title='上传量']/text()"
my_downloaded_rule = "//li[@title='下载量']/text()"
my_ratio_rule = "//li[@title='分享率']/a/text()"
my_bonus_rule = "//li[@title='魔力']/a/text()"
my_per_hour_bonus_rule = "//dt[contains(text(),'每小时获得魔力数量')]/following-sibling::dd[1]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//div[@class='header gradient blue']//h4[1]/span/text()"
my_passkey_rule = "//span[@class='text-monospace']/text()"
my_uid_rule = "//li/a[contains(@href,'users')]/img/@alt"
my_hr_rule = "//strong[contains(text(),'有效')]/text()"
my_leech_rule = "//span[contains(text(),'正在下载')]/a/text()"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//span[contains(text(),'做种数量')]/a/text()"
my_seed_vol_rule = "//td[contains(text(),'做种体积')]/following-sibling::td[1]/span/text()[1]"
my_mailbox_rule = "//a[contains(@href,'mail/inbox')]/*[name()='svg']"
my_message_title = "//td/span[@class='label label-danger']/parent::td/preceding-sibling::td[@class='col-sm-5']/a/text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@id='torrent-list-table']/tbody/tr"
torrent_title_rule = ".//a[@class='view-torrent torrent-listings-name']/text()"
torrent_subtitle_rule = ".//span[@class='view-torrent torrent-listings-subhead']/b/text()"
torrent_detail_url_rule = ".//a[@class='view-torrent torrent-listings-name']/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@title"
torrent_poster_rule = ".//div[@class='body_poster']/img/@src"
torrent_magnet_url_rule = ".//a[@class='view-torrent torrent-listings-name']/following::a[1]/@href"
torrent_size_rule = ".//td[@class='torrent-listings-size']/span//text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//i[contains(@class, 'torrent-flag__freeleech')]/text()"
torrent_sale_expire_rule = ".//i[contains(@class, 'torrent-flag__freeleech')]/@data-original-title"
torrent_release_rule = ".//td[@class='torrent-listings-age']/span/@data-original-title"
torrent_seeders_rule = ".//td[@class='torrent-listings-seeders']//span/text()"
torrent_leechers_rule = ".//td[@class='torrent-listings-leechers']//span/text()"
torrent_completers_rule = ".//td[@class='torrent-listings-completed']//span/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//div[@class='torrent-buttons']/div[@class]/a[1]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//td[@class='torrent-listings-format']/div/span[contains(@class,'label')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents?imdbId={}"
structure = "UNIT3D"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新注册用户拥有250GB的初始上传流量\n可以正常下载/上传，访问论坛"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "1TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以正常下载 / 上传，访问论坛"

[level.SuperUser]
level_id = 3
level = "SuperUser"
days = 9
uploaded = "2TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "访问邀请区"

[level.ExtremeUser]
level_id = 4
level = "ExtremeUser"
days = 13
uploaded = "5TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "自动通过候选、调整隐私设置"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 27
uploaded = "10TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "同上"

[level.Veteran]
level_id = 6
level = "Veteran"
days = 53
uploaded = "15TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "个人全局双倍上传"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "MonikaDesign的尊贵VIP"
