url = [ "https://audiences.me/",]
name = "观众"
nickname = "观众"
logo = "favicon.ico"
tracker = "t.audiences.me|tracker.cinefiles.info"
sp_full = 140
limit_speed = 95
tags = "综合,压制,官组,Diy,原盘,特效字幕,X265,Web,最速Web"
iyuu = 68
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = [ "torrents.php?search={}",]
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//span[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//span[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//span[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='mybonus.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//span[@class='color_bonus']/following-sibling::text()[1]"
my_level_rule = "//td[contains(text(),'等级')]/following-sibling::td[1]/img/@title"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/span[@id='passkey']/text()"
my_uid_rule = "//a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown'][1]/following-sibling::text()[1]"
my_publish_rule = "(/body//b)[1]/text()"
my_seed_rule = "//img[@class='arrowup'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//b/following-sibling::text()[1]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[contains(@class,'torrents')]//tr/td[not(@class)]/parent::tr"
torrent_title_rule = ".//a[contains(@href,'detail')]/b/text()[1]"
torrent_subtitle_rule = ".//tr/td[@class='embedded']/span[last()]/text()"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[@class='torrents-progress']/@style"
torrent_hr_rule = ".//img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//tr/td[@class='embedded']/b/span[last()]/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]//text()"
torrent_leechers_rule = ".//td[7]//text()"
torrent_completers_rule = ".//td[8]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'种子链接')]/following-sibling::td/b/a/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td[contains(text(),'Hash')]/text()"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/div/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=2&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别；可以请求续种。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 100000
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看NFO文档；可以查看用户列表；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕；发布5种通过候选后可直接发布种子。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 15
uploaded = "0"
downloaded = "240GB"
bonus = 0.0
score = 180000
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "同年轻气盛(PowerUser)"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 24
uploaded = "0"
downloaded = "400GB"
bonus = 0.0
score = 320000
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看排行榜。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 40
uploaded = "0"
downloaded = "600GB"
bonus = 0.0
score = 480000
ratio = 3.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "同街头霸王(CrazyUser)"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 60
uploaded = "0"
downloaded = "900GB"
bonus = 0.0
score = 660000
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看其它用户的评论、帖子历史。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 80
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 880000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "可以更新过期的外部信息。头号玩家(ExtremeUser)xa0及以上用户会永远保留账号。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 100
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 1080000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "同头号玩家(ExtremeUser)"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 112
uploaded = "0"
downloaded = "8TB"
bonus = 0.0
score = 1280000
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "同头号玩家(ExtremeUser)"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "由管理员仔细斟酌后分配给他们认为对于站点某方面有特殊贡献的用户。"
